spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dsmovie
    username: postgres
    password: admin
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
        