name: CI

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and run backend
      working-directory: backend
      run: |
        docker build -t backend-image .
        docker run -d -p 8080:8080 --name backend-container backend-image

    - name: Build and run frontend
      working-directory: frontend
      run: |
        docker build -t frontend-image .
        docker run -d -p 3000:3000 --name frontend-container frontend-image

    - name: Wait for services to start
      run: sleep 30

    - name: Run tests (adjust this step based on your needs)
      working-directory: backend
      run: docker exec backend-container ./mvnw test

    - name: Stop and remove containers
      run: |
        docker stop backend-container
        docker rm backend-container
        docker stop frontend-container
        docker rm frontend-container
