name: Build and Deploy

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        working-directory: backend

    - name: Debug Directory Structure
      run: |
        ls -la
        cd backend
        ls -la
        docker-compose -f docker-compose.yml build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy Application
      run: |
        cd backend
        docker-compose -f docker-compose.yml up -d
