name: Build and Deploy

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Images
      run: |
        cd backend
        docker-compose -f docker-compose.yml build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy Application
      run: |
        cd backend
        docker-compose -f docker-compose.yml up -d
